In [1]:
import pandas as pd

In [2]:
data=pd.read_csv("insurance_pre.csv")

In [3]:
data

      age     sex     bmi  children smoker      charges
0      19  female  27.900         0    yes  16884.92400
1      18    male  33.770         1     no   1725.55230
2      28    male  33.000         3     no   4449.46200
3      33    male  22.705         0     no  21984.47061
4      32    male  28.880         0     no   3866.85520
...   ...     ...     ...       ...    ...          ...
1333   50    male  30.970         3     no  10600.54830
1334   18  female  31.920         0     no   2205.98080
1335   18  female  36.850         0     no   1629.83350
1336   21  female  25.800         0     no   2007.94500
1337   61  female  29.070         0    yes  29141.36030

[1338 rows x 6 columns]

In [13]:
data=pd.get_dummies(data,drop_first=True)

In [14]:
data

      age     bmi  children      charges  sex_male  smoker_yes
0      19  27.900         0  16884.92400         0           1
1      18  33.770         1   1725.55230         1           0
2      28  33.000         3   4449.46200         1           0
3      33  22.705         0  21984.47061         1           0
4      32  28.880         0   3866.85520         1           0
...   ...     ...       ...          ...       ...         ...
1333   50  30.970         3  10600.54830         1           0
1334   18  31.920         0   2205.98080         0           0
1335   18  36.850         0   1629.83350         0           0
1336   21  25.800         0   2007.94500         0           0
1337   61  29.070         0  29141.36030         0           1

[1338 rows x 6 columns]

In [15]:
data.columns

Index(['age', 'bmi', 'children', 'charges', 'sex_male', 'smoker_yes'], dtype='object')

In [22]:
independent=data[['age', 'bmi', 'children', 'sex_male', 'smoker_yes']]
dependent=data[['charges']]

In [25]:
from sklearn.model_selection import GridSearchCV
from sklearn.tree import DecisionTreeRegressor
param_grid={"criterion":["mae", "mse","friedman_mse"],
            "splitter":["best","random"],"max_features":["auto","sqrt","log2"]}

grid=GridSearchCV(DecisionTreeRegressor(),param_grid,refit=True,verbose=3,n_jobs=-1)

In [26]:
grid.fit(independent,dependent)

Fitting 5 folds for each of 18 candidates, totalling 90 fits

C:\Users\venka\anaconda3\lib\site-packages\sklearn\tree\_classes.py:366: FutureWarning: Criterion 'mae' was deprecated in v1.0 and will be removed in version 1.2. Use `criterion='absolute_error'` which is equivalent.
  warnings.warn(

GridSearchCV(estimator=DecisionTreeRegressor(), n_jobs=-1,
             param_grid={'criterion': ['mae', 'mse', 'friedman_mse'],
                         'max_features': ['auto', 'sqrt', 'log2'],
                         'splitter': ['best', 'random']},
             verbose=3)

In [27]:

print("The rscore value for best parameter {} :".format(grid.best_params_))

The rscore value for best parameter {'criterion': 'mae', 'max_features': 'sqrt', 'splitter': 'random'} :

In [28]:
results=grid.cv_results_

In [29]:
results

{'mean_fit_time': array([0.27224293, 0.12092957, 0.14831424, 0.28783336, 0.08235149,
        0.08495073, 0.10413895, 0.09014697, 0.19868417, 0.18649201,
        0.0993423 , 0.11413245, 0.01838841, 0.01259193, 0.01119237,
        0.00939407, 0.01119237, 0.01379156]),
 'std_fit_time': array([0.10942269, 0.0082897 , 0.05901769, 0.20275527, 0.00688359,
        0.01102028, 0.12237109, 0.11045079, 0.32502122, 0.3015912 ,
        0.10879515, 0.1518755 , 0.00412511, 0.00471272, 0.00039957,
        0.00048908, 0.00074761, 0.00421249]),
 'mean_score_time': array([0.00639687, 0.00599823, 0.00639644, 0.0141932 , 0.00619769,
        0.00999494, 0.00699654, 0.00779567, 0.00639677, 0.00579691,
        0.02178812, 0.00839648, 0.00619712, 0.00759711, 0.00559702,
        0.00619688, 0.00579705, 0.00659661]),
 'std_score_time': array([0.00048951, 0.00063241, 0.00048947, 0.00577298, 0.00039959,
        0.00619322, 0.00199859, 0.00312191, 0.00048998, 0.0007482 ,
        0.03059211, 0.00286896, 0.00098003, 0.00371945, 0.00048922,
        0.00116538, 0.00074792, 0.00272666]),
 'param_criterion': masked_array(data=['mae', 'mae', 'mae', 'mae', 'mae', 'mae', 'mse', 'mse',
                    'mse', 'mse', 'mse', 'mse', 'friedman_mse',
                    'friedman_mse', 'friedman_mse', 'friedman_mse',
                    'friedman_mse', 'friedman_mse'],
              mask=[False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False],
        fill_value='?',
             dtype=object),
 'param_max_features': masked_array(data=['auto', 'auto', 'sqrt', 'sqrt', 'log2', 'log2', 'auto',
                    'auto', 'sqrt', 'sqrt', 'log2', 'log2', 'auto', 'auto',
                    'sqrt', 'sqrt', 'log2', 'log2'],
              mask=[False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False],
        fill_value='?',
             dtype=object),
 'param_splitter': masked_array(data=['best', 'random', 'best', 'random', 'best', 'random',
                    'best', 'random', 'best', 'random', 'best', 'random',
                    'best', 'random', 'best', 'random', 'best', 'random'],
              mask=[False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False],
        fill_value='?',
             dtype=object),
 'params': [{'criterion': 'mae', 'max_features': 'auto', 'splitter': 'best'},
  {'criterion': 'mae', 'max_features': 'auto', 'splitter': 'random'},
  {'criterion': 'mae', 'max_features': 'sqrt', 'splitter': 'best'},
  {'criterion': 'mae', 'max_features': 'sqrt', 'splitter': 'random'},
  {'criterion': 'mae', 'max_features': 'log2', 'splitter': 'best'},
  {'criterion': 'mae', 'max_features': 'log2', 'splitter': 'random'},
  {'criterion': 'mse', 'max_features': 'auto', 'splitter': 'best'},
  {'criterion': 'mse', 'max_features': 'auto', 'splitter': 'random'},
  {'criterion': 'mse', 'max_features': 'sqrt', 'splitter': 'best'},
  {'criterion': 'mse', 'max_features': 'sqrt', 'splitter': 'random'},
  {'criterion': 'mse', 'max_features': 'log2', 'splitter': 'best'},
  {'criterion': 'mse', 'max_features': 'log2', 'splitter': 'random'},
  {'criterion': 'friedman_mse', 'max_features': 'auto', 'splitter': 'best'},
  {'criterion': 'friedman_mse', 'max_features': 'auto', 'splitter': 'random'},
  {'criterion': 'friedman_mse', 'max_features': 'sqrt', 'splitter': 'best'},
  {'criterion': 'friedman_mse', 'max_features': 'sqrt', 'splitter': 'random'},
  {'criterion': 'friedman_mse', 'max_features': 'log2', 'splitter': 'best'},
  {'criterion': 'friedman_mse', 'max_features': 'log2', 'splitter': 'random'}],
 'split0_test_score': array([0.72419838, 0.62205094, 0.74562997, 0.7775551 , 0.60783012,
        0.67809418, 0.72770811, 0.61158062, 0.685669  , 0.64549392,
        0.74073711, 0.69635314, 0.72320414, 0.66435887, 0.68689994,
        0.61440406, 0.72830272, 0.68503725]),
 'split1_test_score': array([0.60217679, 0.66935071, 0.55633841, 0.62544877, 0.58796662,
        0.55669365, 0.64922803, 0.53813481, 0.63610364, 0.54884733,
        0.66119122, 0.60718523, 0.65648987, 0.63444389, 0.51415544,
        0.48299819, 0.60052308, 0.56608086]),
 'split2_test_score': array([0.70568222, 0.67212422, 0.69501201, 0.78862019, 0.64557382,
        0.7208936 , 0.73144835, 0.732898  , 0.67723027, 0.62401052,
        0.73376239, 0.685793  , 0.73281284, 0.78446899, 0.69542293,
        0.63324226, 0.78618849, 0.61217578]),
 'split3_test_score': array([0.72321834, 0.76563152, 0.71405947, 0.73390777, 0.71386073,
        0.74099536, 0.73902986, 0.73115546, 0.73280874, 0.68865091,
        0.56740543, 0.69802357, 0.70930406, 0.67399206, 0.71828401,
        0.69475119, 0.65399273, 0.65993166]),
 'split4_test_score': array([0.7434379 , 0.72589174, 0.73821285, 0.72885276, 0.74556004,
        0.77507147, 0.6873879 , 0.72274085, 0.717769  , 0.7357258 ,
        0.72603302, 0.71286011, 0.66977093, 0.7045568 , 0.70312001,
        0.72195406, 0.77076146, 0.61953143]),
 'mean_test_score': array([0.69974272, 0.69100983, 0.68985054, 0.73087692, 0.66015827,
        0.69434965, 0.70696045, 0.66730195, 0.68991613, 0.6485457 ,
        0.68582583, 0.68004301, 0.69831637, 0.69236412, 0.66357647,
        0.62946995, 0.7079537 , 0.6285514 ]),
 'std_test_score': array([0.05022517, 0.04973179, 0.06912085, 0.05769145, 0.060564  ,
        0.07564368, 0.03398437, 0.07904758, 0.03373518, 0.0628647 ,
        0.06566587, 0.03743688, 0.02998144, 0.05120263, 0.07542073,
        0.08307844, 0.07061544, 0.04105475]),
 'rank_test_score': array([ 4,  8, 10,  1, 15,  6,  3, 13,  9, 16, 11, 12,  5,  7, 14, 17,  2,
        18])}

In [33]:
table=pd.DataFrame.from_dict(results)

In [34]:
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_criterion,param_max_features,param_splitter,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.272243,0.109423,0.006397,0.000490,mae,auto,best,"{'criterion': 'mae', 'max_features': 'auto', '...",0.724198,0.602177,0.705682,0.723218,0.743438,0.699743,0.050225,4
1,0.120930,0.008290,0.005998,0.000632,mae,auto,random,"{'criterion': 'mae', 'max_features': 'auto', '...",0.622051,0.669351,0.672124,0.765632,0.725892,0.691010,0.049732,8
2,0.148314,0.059018,0.006396,0.000489,mae,sqrt,best,"{'criterion': 'mae', 'max_features': 'sqrt', '...",0.745630,0.556338,0.695012,0.714059,0.738213,0.689851,0.069121,10
3,0.287833,0.202755,0.014193,0.005773,mae,sqrt,random,"{'criterion': 'mae', 'max_features': 'sqrt', '...",0.777555,0.625449,0.788620,0.733908,0.728853,0.730877,0.057691,1
4,0.082351,0.006884,0.006198,0.000400,mae,log2,best,"{'criterion': 'mae', 'max_features': 'log2', '...",0.607830,0.587967,0.645574,0.713861,0.745560,0.660158,0.060564,15
5,0.084951,0.011020,0.009995,0.006193,mae,log2,random,"{'criterion': 'mae', 'max_features': 'log2', '...",0.678094,0.556694,0.720894,0.740995,0.775071,0.694350,0.075644,6
6,0.104139,0.122371,0.006997,0.001999,mse,auto,best,"{'criterion': 'mse', 'max_features': 'auto', '...",0.727708,0.649228,0.731448,0.739030,0.687388,0.706960,0.033984,3
7,0.090147,0.110451,0.007796,0.003122,mse,auto,random,"{'criterion': 'mse', 'max_features': 'auto', '...",0.611581,0.538135,0.732898,0.731155,0.722741,0.667302,0.079048,13
8,0.198684,0.325021,0.006397,0.000490,mse,sqrt,best,"{'criterion': 'mse', 'max_features': 'sqrt', '...",0.685669,0.636104,0.677230,0.732809,0.717769,0.689916,0.033735,9
9,0.186492,0.301591,0.005797,0.000748,mse,sqrt,random,"{'criterion': 'mse', 'max_features': 'sqrt', '...",0.645494,0.548847,0.624011,0.688651,0.735726,0.648546,0.062865,16
10,0.099342,0.108795,0.021788,0.030592,mse,log2,best,"{'criterion': 'mse', 'max_features': 'log2', '...",0.740737,0.661191,0.733762,0.567405,0.726033,0.685826,0.065666,11
11,0.114132,0.151875,0.008396,0.002869,mse,log2,random,"{'criterion': 'mse', 'max_features': 'log2', '...",0.696353,0.607185,0.685793,0.698024,0.712860,0.680043,0.037437,12
12,0.018388,0.004125,0.006197,0.000980,friedman_mse,auto,best,"{'criterion': 'friedman_mse', 'max_features': ...",0.723204,0.656490,0.732813,0.709304,0.669771,0.698316,0.029981,5
13,0.012592,0.004713,0.007597,0.003719,friedman_mse,auto,random,"{'criterion': 'friedman_mse', 'max_features': ...",0.664359,0.634444,0.784469,0.673992,0.704557,0.692364,0.051203,7
14,0.011192,0.000400,0.005597,0.000489,friedman_mse,sqrt,best,"{'criterion': 'friedman_mse', 'max_features': ...",0.686900,0.514155,0.695423,0.718284,0.703120,0.663576,0.075421,14
15,0.009394,0.000489,0.006197,0.001165,friedman_mse,sqrt,random,"{'criterion': 'friedman_mse', 'max_features': ...",0.614404,0.482998,0.633242,0.694751,0.721954,0.629470,0.083078,17
16,0.011192,0.000748,0.005797,0.000748,friedman_mse,log2,best,"{'criterion': 'friedman_mse', 'max_features': ...",0.728303,0.600523,0.786188,0.653993,0.770761,0.707954,0.070615,2
17,0.013792,0.004212,0.006597,0.002727,friedman_mse,log2,random,"{'criterion': 'friedman_mse', 'max_features': ...",0.685037,0.566081,0.612176,0.659932,0.619531,0.628551,0.041055,18

In [37]:
age_input=float(input("Age : "))
bmi_input=float(input("BMI : "))
child_input=int(input("Children: "))
sex_input=int(input("Sex Male 0 or 1 : "))
smoker_s_input=int(input("Smoker yes 0 or 1 : "))

Age : 33
BMI : 31
Children: 2
Sex Male 0 or 1 : 1
Smoker yes 0 or 1 : 1

In [39]:
future_predict=grid.predict([[age_input,bmi_input,child_input,sex_input,smoker_s_input]])

C:\Users\venka\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but DecisionTreeRegressor was fitted with feature names
  warnings.warn(

In [40]:
print("Future Prediction is :{} ".format(future_predict))

Future Prediction is :[34303.1672]